services:
  - type: web
    name: caixinha-republica
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_DIST_PATH
        value: /app/frontend/dist
      - key: ENABLE_PROOFS
        value: "false"
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
